### ISSUE TITLE
Allow multiple image styles

### ISSUE THREAD

**Issue by schlosser** [danrschlosser/eventum#80]
Right now, all images are background images that are set to cover the desired frame (they are cropped to fit).  This is done in css with:

``` css
i {
    background-size: cover;
}
```

We should have a toggle, where images that may readily be cropped are displayed as they are right now, and images like logos, screenshots, etc that should be displayed as `<img>` tags with a `max-width` and `max-height`, or a background image with the css:

``` css
i {
    background-image: contain;
}
```

For example: The headline image in [this blog post](https://adicu.com/blog/post/origins-of-eventum) is pretty underwhelming because it is cropped.

This should be set in the admin interface (when the media item is uploaded) and stored on the image object (in `Image.py`).
